### ISSUE TITLE
[Question] How does one add extra dev tool links in 5.4.1

### ISSUE THREAD

**Issue by mooror** [jonom/silverstripe-betternavigator#66]
I noticed that in the latest release (v6) that the template paths/namespaces were updated. But I am still using Silverstripe 4 and so I'm stuck with version 5.4.1 and cannot seem to figure out how to add extra links to the developer tools section

I have tried `templates/JonoM/BetterNavigator/Includes/BetterNavigatorExtraDevTools.ss`, `templates/BetterNavigator/Includes/ BetterNavigatorExtraDevTools.ss` and `templates/BetterNavigator/BetterNavigator/Includes/ BetterNavigatorExtraDevTools.ss` without any effect (and I made sure to flush after updating the template).

Am I using the wrong paths? Or does this have something to do with me trying to overwrite the template from my own module rather then the theme template folder?

**Comment by mooror** [comment]
Hmmmm... So when I added the template to the `templates/BetterNavigator/Includes/BetterNavigatorExtraDevTools.ss` in my themes folder, it works fine, but not from within my module templates folder :thinking:

**Comment by mooror** [comment]
I think I will need to alter the module priority to load my module before this one for the templates to apply properly

**Comment by mooror** [comment]
For anyone who has this same issue, you just need to boost the priority of your module using the following YAML in a config file (Make sure to replace `"vendor/your-module"` with your modules vendor and name)

```
---
Name: modulepriority
Before:
  - 'jonom/silverstripe-betternavigator'
Only:
  moduleexists:
    - 'jonom/silverstripe-betternavigator'
---

SilverStripe\Core\Manifest\ModuleManifest:
  module_priority:
    - "vendor/your-module"
```
